spring:
  application:
    name: postal-code-consultation-api

  datasource:
    url: jdbc:postgresql://localhost:5432/aircraft-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    #    url: jdbc:mysql://localhost:3306/ww2_aircraft_db
    #    username: root
    #    password: Chico.Maggie2024
    #    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



